### PR TITLE
Heroku restructure

### PR DESCRIPTION
**Pull request by pondorasti**
### Checklist
- [x] Merged `dev` into this branch
- [x] There's no merge conflicts
- [ ] Thoroughly tested code
- [x] Trello card requirements are met

### What's new?
* Separated website from scraper
* Added Heroku `Procfile` config for scraper
* Published initial scraper api to this endpoint: https://stonkscraper.herokuapp.com

### Known Issues
*

### CODE REVIEW

**Comment by numel007** [comment]
Still working on getting files to import correctly?

**Comment by pondorasti** [comment]
@numel007 no lol, I think everything is done, but I want to get your and xila's opinion before we merge it.

**Comment by xilaluna** [comment]
Yo, everything looks good ill start to implement the fetch to the routes python file.

**Review by xilaluna — APPROVED** [review]
everything is good may need to restructure how we use .env for separated applications

**Pull request merged**
